const designedBlocks: any = [
    // {
    //     type: "banners",
    //     thumbnail: "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/61.png",
    //     elements: { "id": "c80cb1fb-9815-ee67-d7e0-dba9e4f888c0", "columnType": "BlockOneColumn", "type": "block", "hovered": false, "options": { "background": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "#FFFFFF" }, "sectionBackground": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "transparent" }, "border": { "size": 0, "style": "solid", "color": "#DDDDDD", "applyTo": ["left", "right", "top", "bottom"] }, "padding": [10, 10, 10, 10], "margin": [0, 0, 0, 0] }, "columns": [{ "id": "6c2ce8a3-6127-1343-b4cc-9caca2fa4d22", "columnWidthPercentage": 100, "contents": [{ "id": "480c460b-4e47-0822-aa26-28ceb73684d7", "type": "image", "hovered": false, "options": { "align": "center", "padding": [0, 0, 0, 0], "image": "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/61.png", "width": 100, "fullWidth": false, "fluidOnMobile": false, "height": 100, "backgroundColor": "transparent", "altTag": "", "border": { "size": 0, "radius": 0, "color": "#3498DB", "style": "solid", "styleOptions": ["dotted", "solid", "dashed"] }, "linkTo": { "type": "none", "typeOptions": ["link", "email", "none"], "link": "" } } }], "options": { "backgroundColor": "transparent", "padding": [10, 10, 10, 10], "border": { "size": 1, "style": "solid", "styleOptions": ["solid", "dashed", "dotted"], "color": "transparent" }, "verticalAlign": "top" } }] }
    // },
    // {
    //     type: "headers",
    //     thumbnail: "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/179.png",
    //     elements: { "id": "c80cb1fb-9815-ee67-d7e0-dba9e4f888c0", "columnType": "BlockOneColumn", "type": "block", "hovered": false, "options": { "background": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "#FFFFFF" }, "sectionBackground": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "transparent" }, "border": { "size": 0, "style": "solid", "color": "#DDDDDD", "applyTo": ["left", "right", "top", "bottom"] }, "padding": [10, 10, 10, 10], "margin": [0, 0, 0, 0] }, "columns": [{ "id": "6c2ce8a3-6127-1343-b4cc-9caca2fa4d22", "columnWidthPercentage": 100, "contents": [{ "id": "480c460b-4e47-0822-aa26-28ceb73684d7", "type": "image", "hovered": false, "options": { "align": "center", "padding": [0, 0, 0, 0], "image": "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/61.png", "width": 100, "fullWidth": false, "fluidOnMobile": false, "height": 100, "backgroundColor": "transparent", "altTag": "", "border": { "size": 0, "radius": 0, "color": "#3498DB", "style": "solid", "styleOptions": ["dotted", "solid", "dashed"] }, "linkTo": { "type": "none", "typeOptions": ["link", "email", "none"], "link": "" } } }], "options": { "backgroundColor": "transparent", "padding": [10, 10, 10, 10], "border": { "size": 1, "style": "solid", "styleOptions": ["solid", "dashed", "dotted"], "color": "transparent" }, "verticalAlign": "top" } }] }
    // },
    // {
    //     type: "headers",
    //     thumbnail: "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/179.png",
    //     elements: { "id": "c80cb1fb-9815-ee67-d7e0-dba9e4f888c0", "columnType": "BlockOneColumn", "type": "block", "hovered": false, "options": { "background": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "#FFFFFF" }, "sectionBackground": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "transparent" }, "border": { "size": 0, "style": "solid", "color": "#DDDDDD", "applyTo": ["left", "right", "top", "bottom"] }, "padding": [10, 10, 10, 10], "margin": [0, 0, 0, 0] }, "columns": [{ "id": "6c2ce8a3-6127-1343-b4cc-9caca2fa4d22", "columnWidthPercentage": 100, "contents": [{ "id": "480c460b-4e47-0822-aa26-28ceb73684d7", "type": "image", "hovered": false, "options": { "align": "center", "padding": [0, 0, 0, 0], "image": "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/61.png", "width": 100, "fullWidth": false, "fluidOnMobile": false, "height": 100, "backgroundColor": "transparent", "altTag": "", "border": { "size": 0, "radius": 0, "color": "#3498DB", "style": "solid", "styleOptions": ["dotted", "solid", "dashed"] }, "linkTo": { "type": "none", "typeOptions": ["link", "email", "none"], "link": "" } } }], "options": { "backgroundColor": "transparent", "padding": [10, 10, 10, 10], "border": { "size": 1, "style": "solid", "styleOptions": ["solid", "dashed", "dotted"], "color": "transparent" }, "verticalAlign": "top" } }] }
    // },
    // {
    //     type: "footer",
    //     thumbnail: "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/190.png",
    //     elements: { "id": "c80cb1fb-9815-ee67-d7e0-dba9e4f888c0", "columnType": "BlockOneColumn", "type": "block", "hovered": false, "options": { "background": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "#FFFFFF" }, "sectionBackground": { "url": "", "noRepeat": true, "size": "cover", "positionX": "center", "positionY": "center", "color": "transparent" }, "border": { "size": 0, "style": "solid", "color": "#DDDDDD", "applyTo": ["left", "right", "top", "bottom"] }, "padding": [10, 10, 10, 10], "margin": [0, 0, 0, 0] }, "columns": [{ "id": "6c2ce8a3-6127-1343-b4cc-9caca2fa4d22", "columnWidthPercentage": 100, "contents": [{ "id": "480c460b-4e47-0822-aa26-28ceb73684d7", "type": "image", "hovered": false, "options": { "align": "center", "padding": [0, 0, 0, 0], "image": "https://d2p078bqz5urf7.cloudfront.net/cloud/landingpage-builder/predesigned/thumbs/61.png", "width": 100, "fullWidth": false, "fluidOnMobile": false, "height": 100, "backgroundColor": "transparent", "altTag": "", "border": { "size": 0, "radius": 0, "color": "#3498DB", "style": "solid", "styleOptions": ["dotted", "solid", "dashed"] }, "linkTo": { "type": "none", "typeOptions": ["link", "email", "none"], "link": "" } } }], "options": { "backgroundColor": "transparent", "padding": [10, 10, 10, 10], "border": { "size": 1, "style": "solid", "styleOptions": ["solid", "dashed", "dotted"], "color": "transparent" }, "verticalAlign": "top" } }] }
    // }
];

export default designedBlocks;


const savedBlocks = {

}